version: 2
jobs:
  build-and-test:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn
            - run: yarn test
workflows:
    build-and-test:
      jobs:
        - build-and-test